name: 'Helm command demo'
description: 'Execute a helm command inside a docker container'
inputs:
  command-arguments:
    description: 'helm command arguments'
    required: true
    default: '--debug'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command-arguments }}
